### ISSUE TITLE
demo.snmplabs.com is down?

### ISSUE THREAD

**Issue by jpldev** [etingof/snmplabs.com#1]
demo.snmplabs.com is down?

$ snmpwalk -v2c -c public demo.snmplabs.com
Timeout: No Response from demo.snmplabs.co

**Comment by etingof** [comment]
Yay, fixed! Thank you for the heads up!

**Comment by grishy** [comment]
Same problem :)
@etingof

**Comment by hossein-eshraghi** [comment]
this problem was not fixed, how to solve it?!
**Timeout: No Response from demo.snmplabs.com**

**Comment by LusineH** [comment]
I have the same issue too: No SNMP response received before timeout

**Comment by LO-RAN** [comment]
same here.
Any alternative ?

**Comment by arezazadeh** [comment]
is snmplabs.com down? its not even pingable

**Comment by cipradu** [comment]
is there any plan to bring it back online?

**Comment by jb-dev-github** [comment]
Same question.

**Comment by dasrfp** [comment]
whois data shows the domain is on clientHold status; per https://www.icann.org/resources/pages/epp-status-codes-2014-06-16-en#clientHold this means:

"This status code tells your domain's registry to not activate your domain in the DNS and as a consequence, it will not resolve. It is an uncommon status that is usually enacted during legal disputes, non-payment, or when your domain is subject to deletion.
"Often, this status indicates an issue with your domain that needs resolution. If so, you should contact your registrar to resolve the issue. If your domain does not have any issues, but you need it to resolve, you must first contact your registrar and request that they remove this status code."

**Comment by zatroa** [comment]
Hey, the Website is now available again but not on the same URL. We use the snmpsim nearly daily, so as we saw that snmplabs.com is not reachable anymore, we decided to recover the website as much as we can. If you want to look at our recovery, click [here](https://snmplabs.thola.io/).
